<?php

require_once('../php/log.php');

$fila = isset($_REQUEST['fila']) ? $_REQUEST['fila'] : -1;

writelog("Fila ".$fila);
$result = '{"total":0,"rows":[]}';

if($fila==0){
	
$result = <<<MSG
{"total":4,"rows":[
{"AGE_HORA":"08:00","AGE_TIPORESREVA":"1","AGE_APEYNOMPAC":"PEREZ, JUAN","AGE_IDAFIL":"12345","AGE_TELEFONO":"4554-4321","AGE_MOTIVO":"Consulta"},
{"AGE_HORA":"08:10","AGE_TIPORESREVA":"2","AGE_APEYNOMPAC":"YURIA, PEDRO","AGE_IDAFIL":"12345","AGE_TELEFONO":"4554-4321","AGE_MOTIVO":"Consulta"},
{"AGE_HORA":"08:20","AGE_TIPORESREVA":"3","AGE_APEYNOMPAC":"MERITO, SANDRA","AGE_IDAFIL":"12345","AGE_TELEFONO":"4554-4321","AGE_MOTIVO":"Consulta"},
{"AGE_HORA":"08:30","AGE_TIPORESREVA":"4","AGE_APEYNOMPAC":"OLMOS, ERMINIO","AGE_IDAFIL":"12345","AGE_TELEFONO":"4554-4321","AGE_MOTIVO":"Consulta"}
]}	
MSG;

}
if($fila==1){

$result = <<<MSG
{"total":4,"rows":[
{"AGE_HORA":"17:10","AGE_TIPORESREVA":"2","AGE_APEYNOMPAC":"YURIA, PEDRO","AGE_IDAFIL":"12345","AGE_TELEFONO":"4554-4321","AGE_MOTIVO":"Consulta"},
{"AGE_HORA":"17:20","AGE_TIPORESREVA":"","AGE_APEYNOMPAC":"","AGE_IDAFIL":"","AGE_TELEFONO":"","AGE_MOTIVO":""},
{"AGE_HORA":"17:30","AGE_TIPORESREVA":"3","AGE_APEYNOMPAC":"MERITO, SANDRA","AGE_IDAFIL":"12345","AGE_TELEFONO":"4554-4321","AGE_MOTIVO":"Consulta"},
{"AGE_HORA":"17:40","AGE_TIPORESREVA":"1","AGE_APEYNOMPAC":"PEREZ, JUAN","AGE_IDAFIL":"12345","AGE_TELEFONO":"4554-4321","AGE_MOTIVO":"Consulta"},
{"AGE_HORA":"17:50","AGE_TIPORESREVA":"","AGE_APEYNOMPAC":"","AGE_IDAFIL":"","AGE_TELEFONO":"","AGE_MOTIVO":""},
{"AGE_HORA":"18:00","AGE_TIPORESREVA":"4","AGE_APEYNOMPAC":"OLMOS, ERMINIO","AGE_IDAFIL":"12345","AGE_TELEFONO":"4554-4321","AGE_MOTIVO":"Consulta"}
]}	
MSG;

}


if($fila==2){
$result = <<<MSG
{"total":4,"rows":[
{"AGE_HORA":"13:10","AGE_TIPORESREVA":"","AGE_APEYNOMPAC":"","AGE_IDAFIL":"","AGE_TELEFONO":"","AGE_MOTIVO":""},
{"AGE_HORA":"13:20","AGE_TIPORESREVA":"","AGE_APEYNOMPAC":"","AGE_IDAFIL":"","AGE_TELEFONO":"","AGE_MOTIVO":""},
{"AGE_HORA":"13:30","AGE_TIPORESREVA":"","AGE_APEYNOMPAC":"","AGE_IDAFIL":"","AGE_TELEFONO":"","AGE_MOTIVO":""},
{"AGE_HORA":"13:40","AGE_TIPORESREVA":"","AGE_APEYNOMPAC":"","AGE_IDAFIL":"","AGE_TELEFONO":"","AGE_MOTIVO":""}
]}	
MSG;

}

writelog($result);
 echo $result

?>